# Generated by Django 4.1 on 2022-08-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="edited",
        ),
    ]
